export const SEARCH_WORD = "SEARCH_WORD";
export const SELECT_WORD = "SELECT_WORD";
export const LOAD_BOOKS = "LOAD_BOOKS";
export const SELECT_BOOK = "SELECT_BOOK";
export const SAVE_BOOK_EDIT = "SAVE_BOOK_EDIT";
export const SAVE_BOOK_EDIT_SUCCESS = "SAVE_BOOK_SUCCESS";
export const SAVE_BOOK_EDIT_FAILURE = "SAVE_BOOK_FAILURE";
export const SAVE_BOOK_NEW = "SAVE_BOOK_NEW";
export const SAVE_BOOK_NEW_SUCCESS = "SAVE_BOOK_NEW_SUCCESS";
export const SAVE_BOOK_NEW_FAILURE = "SAVE_BOOK_NEW_FAILURE";
export const LOAD_DEFAULT_QUOTES = "LOAD_DEFAULT_QUOTES";
export const LOAD_NEXT_QUOTES = "LOAD_NEXT_QUOTES";
export const LOAD_NEXT_QUOTES_ERROR = "LOAD_NEXT_QUOTES_ERROR";

